[[material]]
mg = 82
eg = 94

[[material]]
mg = 337
eg = 281

[[material]]
mg = 365
eg = 297

[[material]]
mg = 477
eg = 512

[[material]]
mg = 1025
eg = 936

[bishop_pair_bonus]
mg = 20
eg = 50

[castling_bonus]
mg = 30
eg = 0

[pawn_shield_full]
mg = 25
eg = 0

[pawn_shield_partial]
mg = 10
eg = 0

[open_file_penalty]
mg = -20
eg = 0

[semi_open_file_penalty]
mg = -10
eg = 0

[isolated_penalty]
mg = -10
eg = -20

[doubled_penalty]
mg = -10
eg = -20

[backward_penalty]
mg = -5
eg = -10

[[passed_pawn_scores]]
mg = 0
eg = 0

[[passed_pawn_scores]]
mg = 5
eg = 10

[[passed_pawn_scores]]
mg = 10
eg = 20

[[passed_pawn_scores]]
mg = 20
eg = 40

[[passed_pawn_scores]]
mg = 40
eg = 80

[[passed_pawn_scores]]
mg = 80
eg = 160

[[passed_pawn_scores]]
mg = 150
eg = 300

[[passed_pawn_scores]]
mg = 0
eg = 0

[connected_bonus]
mg = 5
eg = 10

[rook_open_file_bonus]
mg = 30
eg = 15

[rook_semi_file_bonus]
mg = 15
eg = 10

[knight_outpost_bonus]
mg = 30
eg = 20

[tempo_bonus]
mg = 15
eg = 5

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 98
eg = 178

[[psts]]
mg = 134
eg = 173

[[psts]]
mg = 61
eg = 158

[[psts]]
mg = 95
eg = 134

[[psts]]
mg = 68
eg = 147

[[psts]]
mg = 126
eg = 132

[[psts]]
mg = 34
eg = 165

[[psts]]
mg = -11
eg = 187

[[psts]]
mg = -6
eg = 94

[[psts]]
mg = 7
eg = 100

[[psts]]
mg = 26
eg = 85

[[psts]]
mg = 31
eg = 67

[[psts]]
mg = 65
eg = 56

[[psts]]
mg = 56
eg = 53

[[psts]]
mg = 25
eg = 82

[[psts]]
mg = -20
eg = 84

[[psts]]
mg = -14
eg = 32

[[psts]]
mg = 13
eg = 24

[[psts]]
mg = 6
eg = 13

[[psts]]
mg = 21
eg = 5

[[psts]]
mg = 23
eg = -2

[[psts]]
mg = 12
eg = 4

[[psts]]
mg = 17
eg = 17

[[psts]]
mg = -23
eg = 17

[[psts]]
mg = -27
eg = 13

[[psts]]
mg = -2
eg = 9

[[psts]]
mg = -5
eg = -3

[[psts]]
mg = 12
eg = -7

[[psts]]
mg = 17
eg = -7

[[psts]]
mg = 6
eg = -8

[[psts]]
mg = 10
eg = 3

[[psts]]
mg = -25
eg = -1

[[psts]]
mg = -26
eg = 4

[[psts]]
mg = -4
eg = 7

[[psts]]
mg = -4
eg = -6

[[psts]]
mg = -10
eg = 1

[[psts]]
mg = 3
eg = 0

[[psts]]
mg = 3
eg = -5

[[psts]]
mg = 33
eg = -1

[[psts]]
mg = -12
eg = -8

[[psts]]
mg = -35
eg = 13

[[psts]]
mg = -1
eg = 8

[[psts]]
mg = -20
eg = 8

[[psts]]
mg = -23
eg = 10

[[psts]]
mg = -15
eg = 13

[[psts]]
mg = 24
eg = 0

[[psts]]
mg = 38
eg = 2

[[psts]]
mg = -22
eg = -7

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -167
eg = -58

[[psts]]
mg = -89
eg = -38

[[psts]]
mg = -34
eg = -13

[[psts]]
mg = -49
eg = -28

[[psts]]
mg = 61
eg = -31

[[psts]]
mg = -97
eg = -27

[[psts]]
mg = -15
eg = -63

[[psts]]
mg = -107
eg = -99

[[psts]]
mg = -73
eg = -25

[[psts]]
mg = -41
eg = -8

[[psts]]
mg = 72
eg = -25

[[psts]]
mg = 36
eg = -2

[[psts]]
mg = 23
eg = -9

[[psts]]
mg = 62
eg = -25

[[psts]]
mg = 7
eg = -24

[[psts]]
mg = -17
eg = -52

[[psts]]
mg = -47
eg = -24

[[psts]]
mg = 60
eg = -20

[[psts]]
mg = 37
eg = 10

[[psts]]
mg = 65
eg = 9

[[psts]]
mg = 84
eg = -1

[[psts]]
mg = 129
eg = -9

[[psts]]
mg = 73
eg = -19

[[psts]]
mg = 44
eg = -41

[[psts]]
mg = -9
eg = -17

[[psts]]
mg = 17
eg = 3

[[psts]]
mg = 19
eg = 22

[[psts]]
mg = 53
eg = 22

[[psts]]
mg = 37
eg = 22

[[psts]]
mg = 69
eg = 11

[[psts]]
mg = 18
eg = 8

[[psts]]
mg = 22
eg = -18

[[psts]]
mg = -13
eg = -18

[[psts]]
mg = 4
eg = -6

[[psts]]
mg = 16
eg = 16

[[psts]]
mg = 13
eg = 25

[[psts]]
mg = 28
eg = 16

[[psts]]
mg = 19
eg = 17

[[psts]]
mg = 21
eg = 4

[[psts]]
mg = -8
eg = -18

[[psts]]
mg = -23
eg = -23

[[psts]]
mg = -9
eg = -3

[[psts]]
mg = 12
eg = -1

[[psts]]
mg = 10
eg = 15

[[psts]]
mg = 19
eg = 10

[[psts]]
mg = 17
eg = -3

[[psts]]
mg = 25
eg = -20

[[psts]]
mg = -16
eg = -22

[[psts]]
mg = -29
eg = -42

[[psts]]
mg = -53
eg = -20

[[psts]]
mg = -12
eg = -10

[[psts]]
mg = -3
eg = -5

[[psts]]
mg = -1
eg = -2

[[psts]]
mg = 18
eg = -20

[[psts]]
mg = -14
eg = -23

[[psts]]
mg = -19
eg = -44

[[psts]]
mg = -105
eg = -29

[[psts]]
mg = -21
eg = -51

[[psts]]
mg = -58
eg = -23

[[psts]]
mg = -33
eg = -15

[[psts]]
mg = -17
eg = -22

[[psts]]
mg = -28
eg = -18

[[psts]]
mg = -19
eg = -50

[[psts]]
mg = -23
eg = -64

[[psts]]
mg = -29
eg = -14

[[psts]]
mg = 4
eg = -21

[[psts]]
mg = -82
eg = -11

[[psts]]
mg = -37
eg = -8

[[psts]]
mg = -25
eg = -7

[[psts]]
mg = -42
eg = -9

[[psts]]
mg = 7
eg = -17

[[psts]]
mg = -8
eg = -24

[[psts]]
mg = -26
eg = -8

[[psts]]
mg = 16
eg = -4

[[psts]]
mg = -18
eg = 7

[[psts]]
mg = -13
eg = -12

[[psts]]
mg = 30
eg = -3

[[psts]]
mg = 59
eg = -13

[[psts]]
mg = 18
eg = -4

[[psts]]
mg = -47
eg = -14

[[psts]]
mg = -16
eg = 2

[[psts]]
mg = 37
eg = -8

[[psts]]
mg = 43
eg = 0

[[psts]]
mg = 40
eg = -1

[[psts]]
mg = 35
eg = -2

[[psts]]
mg = 50
eg = 6

[[psts]]
mg = 37
eg = 0

[[psts]]
mg = -2
eg = 4

[[psts]]
mg = -4
eg = -3

[[psts]]
mg = 5
eg = 9

[[psts]]
mg = 19
eg = 12

[[psts]]
mg = 50
eg = 9

[[psts]]
mg = 37
eg = 14

[[psts]]
mg = 37
eg = 10

[[psts]]
mg = 7
eg = 3

[[psts]]
mg = -2
eg = 2

[[psts]]
mg = -6
eg = -6

[[psts]]
mg = 13
eg = 3

[[psts]]
mg = 13
eg = 13

[[psts]]
mg = 26
eg = 19

[[psts]]
mg = 34
eg = 7

[[psts]]
mg = 12
eg = 10

[[psts]]
mg = 10
eg = -3

[[psts]]
mg = 4
eg = -9

[[psts]]
mg = 0
eg = -12

[[psts]]
mg = 15
eg = -3

[[psts]]
mg = 15
eg = 8

[[psts]]
mg = 15
eg = 10

[[psts]]
mg = 14
eg = 13

[[psts]]
mg = 27
eg = 3

[[psts]]
mg = 18
eg = -7

[[psts]]
mg = 10
eg = -15

[[psts]]
mg = 4
eg = -14

[[psts]]
mg = 15
eg = -18

[[psts]]
mg = 16
eg = -7

[[psts]]
mg = 0
eg = -1

[[psts]]
mg = 7
eg = 4

[[psts]]
mg = 21
eg = -9

[[psts]]
mg = 33
eg = -15

[[psts]]
mg = 1
eg = -27

[[psts]]
mg = -33
eg = -23

[[psts]]
mg = -3
eg = -9

[[psts]]
mg = -14
eg = -23

[[psts]]
mg = -21
eg = -5

[[psts]]
mg = -13
eg = -9

[[psts]]
mg = -12
eg = -16

[[psts]]
mg = -39
eg = -5

[[psts]]
mg = -21
eg = -17

[[psts]]
mg = 32
eg = 13

[[psts]]
mg = 42
eg = 10

[[psts]]
mg = 32
eg = 18

[[psts]]
mg = 51
eg = 15

[[psts]]
mg = 63
eg = 12

[[psts]]
mg = 9
eg = 12

[[psts]]
mg = 31
eg = 8

[[psts]]
mg = 43
eg = 5

[[psts]]
mg = 27
eg = 11

[[psts]]
mg = 32
eg = 13

[[psts]]
mg = 58
eg = 13

[[psts]]
mg = 62
eg = 11

[[psts]]
mg = 80
eg = -3

[[psts]]
mg = 67
eg = 3

[[psts]]
mg = 26
eg = 8

[[psts]]
mg = 44
eg = 3

[[psts]]
mg = -5
eg = 7

[[psts]]
mg = 19
eg = 7

[[psts]]
mg = 26
eg = 7

[[psts]]
mg = 36
eg = 5

[[psts]]
mg = 17
eg = 4

[[psts]]
mg = 45
eg = -3

[[psts]]
mg = 61
eg = -5

[[psts]]
mg = 16
eg = -3

[[psts]]
mg = -24
eg = 4

[[psts]]
mg = -11
eg = 3

[[psts]]
mg = 7
eg = 13

[[psts]]
mg = 26
eg = 1

[[psts]]
mg = 24
eg = 2

[[psts]]
mg = 35
eg = 1

[[psts]]
mg = -8
eg = -1

[[psts]]
mg = -20
eg = 2

[[psts]]
mg = -36
eg = 3

[[psts]]
mg = -26
eg = 5

[[psts]]
mg = -12
eg = 8

[[psts]]
mg = -1
eg = 4

[[psts]]
mg = 9
eg = -5

[[psts]]
mg = -7
eg = -6

[[psts]]
mg = 6
eg = -8

[[psts]]
mg = -23
eg = -11

[[psts]]
mg = -45
eg = -4

[[psts]]
mg = -25
eg = 0

[[psts]]
mg = -16
eg = -5

[[psts]]
mg = -17
eg = -1

[[psts]]
mg = 3
eg = -7

[[psts]]
mg = 0
eg = -12

[[psts]]
mg = -5
eg = -8

[[psts]]
mg = -33
eg = -16

[[psts]]
mg = -44
eg = -6

[[psts]]
mg = -16
eg = -6

[[psts]]
mg = -20
eg = 0

[[psts]]
mg = -9
eg = 2

[[psts]]
mg = -1
eg = -9

[[psts]]
mg = 11
eg = -9

[[psts]]
mg = -6
eg = -11

[[psts]]
mg = -71
eg = -3

[[psts]]
mg = -19
eg = -9

[[psts]]
mg = -13
eg = 2

[[psts]]
mg = 1
eg = 3

[[psts]]
mg = 17
eg = -1

[[psts]]
mg = 16
eg = -5

[[psts]]
mg = 7
eg = -13

[[psts]]
mg = -37
eg = 4

[[psts]]
mg = -26
eg = -20

[[psts]]
mg = -28
eg = -9

[[psts]]
mg = 0
eg = 22

[[psts]]
mg = 29
eg = 22

[[psts]]
mg = 12
eg = 27

[[psts]]
mg = 59
eg = 27

[[psts]]
mg = 44
eg = 19

[[psts]]
mg = 43
eg = 10

[[psts]]
mg = 45
eg = 20

[[psts]]
mg = -24
eg = -17

[[psts]]
mg = -39
eg = 20

[[psts]]
mg = -5
eg = 32

[[psts]]
mg = 1
eg = 41

[[psts]]
mg = -16
eg = 58

[[psts]]
mg = 57
eg = 25

[[psts]]
mg = 28
eg = 30

[[psts]]
mg = 54
eg = 0

[[psts]]
mg = -13
eg = -20

[[psts]]
mg = -17
eg = 6

[[psts]]
mg = 7
eg = 9

[[psts]]
mg = 8
eg = 49

[[psts]]
mg = 29
eg = 47

[[psts]]
mg = 56
eg = 35

[[psts]]
mg = 47
eg = 19

[[psts]]
mg = 57
eg = 9

[[psts]]
mg = -27
eg = 3

[[psts]]
mg = -27
eg = 22

[[psts]]
mg = -16
eg = 24

[[psts]]
mg = -16
eg = 45

[[psts]]
mg = -1
eg = 57

[[psts]]
mg = 17
eg = 40

[[psts]]
mg = -2
eg = 57

[[psts]]
mg = 1
eg = 36

[[psts]]
mg = -9
eg = -18

[[psts]]
mg = -26
eg = 28

[[psts]]
mg = -9
eg = 19

[[psts]]
mg = -10
eg = 47

[[psts]]
mg = -2
eg = 31

[[psts]]
mg = -4
eg = 34

[[psts]]
mg = 3
eg = 39

[[psts]]
mg = -3
eg = 23

[[psts]]
mg = -14
eg = -16

[[psts]]
mg = 2
eg = -27

[[psts]]
mg = -11
eg = 15

[[psts]]
mg = -2
eg = 6

[[psts]]
mg = -5
eg = 9

[[psts]]
mg = 2
eg = 17

[[psts]]
mg = 14
eg = 10

[[psts]]
mg = 5
eg = 5

[[psts]]
mg = -35
eg = -22

[[psts]]
mg = -8
eg = -23

[[psts]]
mg = 11
eg = -30

[[psts]]
mg = 2
eg = -16

[[psts]]
mg = 8
eg = -16

[[psts]]
mg = 15
eg = -23

[[psts]]
mg = -3
eg = -36

[[psts]]
mg = 1
eg = -32

[[psts]]
mg = -1
eg = -33

[[psts]]
mg = -18
eg = -28

[[psts]]
mg = -9
eg = -22

[[psts]]
mg = 10
eg = -43

[[psts]]
mg = -15
eg = -5

[[psts]]
mg = -25
eg = -32

[[psts]]
mg = -31
eg = -20

[[psts]]
mg = -50
eg = -41

[[psts]]
mg = -65
eg = -74

[[psts]]
mg = 23
eg = -35

[[psts]]
mg = 16
eg = -18

[[psts]]
mg = -15
eg = -18

[[psts]]
mg = -56
eg = -11

[[psts]]
mg = -34
eg = 15

[[psts]]
mg = 2
eg = 4

[[psts]]
mg = 13
eg = -17

[[psts]]
mg = 29
eg = -12

[[psts]]
mg = -1
eg = 17

[[psts]]
mg = -20
eg = 14

[[psts]]
mg = -7
eg = 17

[[psts]]
mg = -8
eg = 17

[[psts]]
mg = -4
eg = 38

[[psts]]
mg = -38
eg = 23

[[psts]]
mg = -29
eg = 11

[[psts]]
mg = -9
eg = 10

[[psts]]
mg = 24
eg = 17

[[psts]]
mg = 2
eg = 23

[[psts]]
mg = -16
eg = 15

[[psts]]
mg = -20
eg = 20

[[psts]]
mg = 6
eg = 45

[[psts]]
mg = 22
eg = 44

[[psts]]
mg = -22
eg = 13

[[psts]]
mg = -17
eg = -8

[[psts]]
mg = -20
eg = 22

[[psts]]
mg = -12
eg = 24

[[psts]]
mg = -27
eg = 27

[[psts]]
mg = -30
eg = 26

[[psts]]
mg = -25
eg = 33

[[psts]]
mg = -14
eg = 26

[[psts]]
mg = -36
eg = 3

[[psts]]
mg = -49
eg = -18

[[psts]]
mg = -1
eg = -4

[[psts]]
mg = -27
eg = 21

[[psts]]
mg = -39
eg = 24

[[psts]]
mg = -46
eg = 27

[[psts]]
mg = -44
eg = 23

[[psts]]
mg = -33
eg = 9

[[psts]]
mg = -51
eg = -11

[[psts]]
mg = -14
eg = -19

[[psts]]
mg = -14
eg = -3

[[psts]]
mg = -22
eg = 11

[[psts]]
mg = -46
eg = 21

[[psts]]
mg = -44
eg = 23

[[psts]]
mg = -30
eg = 16

[[psts]]
mg = -15
eg = 7

[[psts]]
mg = -27
eg = -9

[[psts]]
mg = 1
eg = -27

[[psts]]
mg = 7
eg = -11

[[psts]]
mg = -8
eg = 4

[[psts]]
mg = -64
eg = 13

[[psts]]
mg = -43
eg = 14

[[psts]]
mg = -16
eg = 4

[[psts]]
mg = 9
eg = -5

[[psts]]
mg = 8
eg = -17

[[psts]]
mg = -15
eg = -53

[[psts]]
mg = 36
eg = -34

[[psts]]
mg = 12
eg = -21

[[psts]]
mg = -54
eg = -11

[[psts]]
mg = 8
eg = -28

[[psts]]
mg = -28
eg = -14

[[psts]]
mg = 24
eg = -24

[[psts]]
mg = 14
eg = -43
