[[material]]
mg = 100
eg = 178

[[material]]
mg = 404
eg = 647

[[material]]
mg = 405
eg = 611

[[material]]
mg = 540
eg = 1128

[[material]]
mg = 1347
eg = 2136

[bishop_pair_bonus]
mg = 22
eg = 123

[castling_bonus]
mg = 13
eg = 0

[pawn_shield_full]
mg = 23
eg = -9

[pawn_shield_partial]
mg = 14
eg = -5

[open_file_penalty]
mg = -51
eg = -14

[semi_open_file_penalty]
mg = -43
eg = 27

[isolated_penalty]
mg = -14
eg = -22

[doubled_penalty]
mg = -1
eg = -17

[backward_penalty]
mg = -11
eg = -19

[[passed_pawn_scores]]
mg = 0
eg = 0

[[passed_pawn_scores]]
mg = -10
eg = 27

[[passed_pawn_scores]]
mg = -24
eg = 34

[[passed_pawn_scores]]
mg = -14
eg = 72

[[passed_pawn_scores]]
mg = 22
eg = 104

[[passed_pawn_scores]]
mg = 45
eg = 203

[[passed_pawn_scores]]
mg = 172
eg = 293

[[passed_pawn_scores]]
mg = 0
eg = 0

[connected_bonus]
mg = 0
eg = 5

[rook_open_file_bonus]
mg = 51
eg = 13

[rook_semi_file_bonus]
mg = 18
eg = 22

[knight_outpost_bonus]
mg = 1
eg = 46

[tempo_bonus]
mg = 15
eg = 19

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_knight]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_bishop]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_rook]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[mobility_queen]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -3
eg = 44

[[psts]]
mg = -2
eg = 41

[[psts]]
mg = -4
eg = 56

[[psts]]
mg = -5
eg = 55

[[psts]]
mg = -4
eg = 59

[[psts]]
mg = 17
eg = 67

[[psts]]
mg = 27
eg = 39

[[psts]]
mg = -10
eg = 23

[[psts]]
mg = 1
eg = 35

[[psts]]
mg = 3
eg = 34

[[psts]]
mg = 7
eg = 37

[[psts]]
mg = 10
eg = 32

[[psts]]
mg = 25
eg = 39

[[psts]]
mg = 10
eg = 50

[[psts]]
mg = 21
eg = 35

[[psts]]
mg = -3
eg = 27

[[psts]]
mg = 2
eg = 48

[[psts]]
mg = 9
eg = 47

[[psts]]
mg = 20
eg = 30

[[psts]]
mg = 31
eg = 24

[[psts]]
mg = 41
eg = 24

[[psts]]
mg = 23
eg = 40

[[psts]]
mg = 12
eg = 43

[[psts]]
mg = -8
eg = 38

[[psts]]
mg = 18
eg = 78

[[psts]]
mg = 32
eg = 69

[[psts]]
mg = 37
eg = 50

[[psts]]
mg = 60
eg = 20

[[psts]]
mg = 76
eg = 24

[[psts]]
mg = 59
eg = 41

[[psts]]
mg = 31
eg = 64

[[psts]]
mg = 4
eg = 63

[[psts]]
mg = 15
eg = 126

[[psts]]
mg = 62
eg = 108

[[psts]]
mg = 93
eg = 65

[[psts]]
mg = 91
eg = 15

[[psts]]
mg = 110
eg = 7

[[psts]]
mg = 147
eg = 43

[[psts]]
mg = 78
eg = 82

[[psts]]
mg = 6
eg = 99

[[psts]]
mg = 84
eg = 95

[[psts]]
mg = 56
eg = 98

[[psts]]
mg = 99
eg = 44

[[psts]]
mg = 117
eg = -8

[[psts]]
mg = 115
eg = -17

[[psts]]
mg = 54
eg = 20

[[psts]]
mg = -127
eg = 109

[[psts]]
mg = -97
eg = 109

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -68
eg = -61

[[psts]]
mg = -14
eg = -35

[[psts]]
mg = -13
eg = 17

[[psts]]
mg = -17
eg = 42

[[psts]]
mg = -8
eg = 45

[[psts]]
mg = 0
eg = 29

[[psts]]
mg = -9
eg = -16

[[psts]]
mg = -60
eg = -79

[[psts]]
mg = -25
eg = 19

[[psts]]
mg = -32
eg = 59

[[psts]]
mg = 7
eg = 62

[[psts]]
mg = 24
eg = 82

[[psts]]
mg = 17
eg = 88

[[psts]]
mg = 20
eg = 59

[[psts]]
mg = -5
eg = 50

[[psts]]
mg = 4
eg = 19

[[psts]]
mg = -7
eg = 9

[[psts]]
mg = 25
eg = 75

[[psts]]
mg = 38
eg = 106

[[psts]]
mg = 51
eg = 127

[[psts]]
mg = 57
eg = 124

[[psts]]
mg = 51
eg = 107

[[psts]]
mg = 40
eg = 82

[[psts]]
mg = 10
eg = 13

[[psts]]
mg = 13
eg = 57

[[psts]]
mg = 42
eg = 98

[[psts]]
mg = 57
eg = 129

[[psts]]
mg = 58
eg = 141

[[psts]]
mg = 69
eg = 145

[[psts]]
mg = 54
eg = 130

[[psts]]
mg = 73
eg = 98

[[psts]]
mg = 31
eg = 65

[[psts]]
mg = 29
eg = 57

[[psts]]
mg = 55
eg = 97

[[psts]]
mg = 91
eg = 133

[[psts]]
mg = 98
eg = 154

[[psts]]
mg = 81
eg = 158

[[psts]]
mg = 112
eg = 133

[[psts]]
mg = 72
eg = 114

[[psts]]
mg = 49
eg = 70

[[psts]]
mg = 11
eg = 41

[[psts]]
mg = 59
eg = 87

[[psts]]
mg = 113
eg = 124

[[psts]]
mg = 129
eg = 127

[[psts]]
mg = 178
eg = 110

[[psts]]
mg = 164
eg = 119

[[psts]]
mg = 112
eg = 79

[[psts]]
mg = 44
eg = 47

[[psts]]
mg = 3
eg = 11

[[psts]]
mg = 8
eg = 59

[[psts]]
mg = 83
eg = 83

[[psts]]
mg = 137
eg = 111

[[psts]]
mg = 116
eg = 112

[[psts]]
mg = 149
eg = 63

[[psts]]
mg = -1
eg = 57

[[psts]]
mg = 32
eg = 11

[[psts]]
mg = -250
eg = -66

[[psts]]
mg = -116
eg = 46

[[psts]]
mg = -128
eg = 112

[[psts]]
mg = 14
eg = 75

[[psts]]
mg = 64
eg = 68

[[psts]]
mg = -115
eg = 116

[[psts]]
mg = -137
eg = 69

[[psts]]
mg = -177
eg = -102

[[psts]]
mg = 35
eg = 26

[[psts]]
mg = 14
eg = 46

[[psts]]
mg = 4
eg = 40

[[psts]]
mg = 2
eg = 57

[[psts]]
mg = -3
eg = 61

[[psts]]
mg = 13
eg = 55

[[psts]]
mg = 7
eg = 50

[[psts]]
mg = 24
eg = 20

[[psts]]
mg = 30
eg = 40

[[psts]]
mg = 35
eg = 39

[[psts]]
mg = 30
eg = 56

[[psts]]
mg = 13
eg = 67

[[psts]]
mg = 21
eg = 65

[[psts]]
mg = 28
eg = 54

[[psts]]
mg = 50
eg = 51

[[psts]]
mg = 33
eg = 8

[[psts]]
mg = 17
eg = 63

[[psts]]
mg = 41
eg = 81

[[psts]]
mg = 29
eg = 82

[[psts]]
mg = 33
eg = 84

[[psts]]
mg = 26
eg = 87

[[psts]]
mg = 37
eg = 78

[[psts]]
mg = 42
eg = 76

[[psts]]
mg = 41
eg = 67

[[psts]]
mg = 10
eg = 69

[[psts]]
mg = 22
eg = 84

[[psts]]
mg = 31
eg = 100

[[psts]]
mg = 47
eg = 91

[[psts]]
mg = 51
eg = 86

[[psts]]
mg = 17
eg = 99

[[psts]]
mg = 27
eg = 84

[[psts]]
mg = 14
eg = 68

[[psts]]
mg = 2
eg = 86

[[psts]]
mg = 42
eg = 99

[[psts]]
mg = 38
eg = 91

[[psts]]
mg = 87
eg = 89

[[psts]]
mg = 64
eg = 99

[[psts]]
mg = 51
eg = 91

[[psts]]
mg = 33
eg = 108

[[psts]]
mg = 15
eg = 92

[[psts]]
mg = 18
eg = 85

[[psts]]
mg = 37
eg = 104

[[psts]]
mg = 66
eg = 88

[[psts]]
mg = 57
eg = 88

[[psts]]
mg = 91
eg = 85

[[psts]]
mg = 78
eg = 96

[[psts]]
mg = 73
eg = 99

[[psts]]
mg = 30
eg = 91

[[psts]]
mg = -50
eg = 86

[[psts]]
mg = 6
eg = 98

[[psts]]
mg = 4
eg = 101

[[psts]]
mg = -18
eg = 103

[[psts]]
mg = 7
eg = 97

[[psts]]
mg = 31
eg = 98

[[psts]]
mg = 0
eg = 98

[[psts]]
mg = -4
eg = 74

[[psts]]
mg = -59
eg = 109

[[psts]]
mg = -83
eg = 119

[[psts]]
mg = -147
eg = 122

[[psts]]
mg = -133
eg = 129

[[psts]]
mg = -100
eg = 122

[[psts]]
mg = -152
eg = 119

[[psts]]
mg = -13
eg = 100

[[psts]]
mg = -44
eg = 105

[[psts]]
mg = 6
eg = 81

[[psts]]
mg = 15
eg = 94

[[psts]]
mg = 24
eg = 98

[[psts]]
mg = 36
eg = 88

[[psts]]
mg = 32
eg = 88

[[psts]]
mg = 36
eg = 100

[[psts]]
mg = 38
eg = 86

[[psts]]
mg = 24
eg = 62

[[psts]]
mg = -77
eg = 89

[[psts]]
mg = -9
eg = 78

[[psts]]
mg = -2
eg = 91

[[psts]]
mg = 4
eg = 86

[[psts]]
mg = 4
eg = 85

[[psts]]
mg = 28
eg = 73

[[psts]]
mg = 30
eg = 66

[[psts]]
mg = -67
eg = 87

[[psts]]
mg = -29
eg = 88

[[psts]]
mg = 0
eg = 109

[[psts]]
mg = -13
eg = 108

[[psts]]
mg = -4
eg = 101

[[psts]]
mg = -3
eg = 101

[[psts]]
mg = 4
eg = 104

[[psts]]
mg = 42
eg = 98

[[psts]]
mg = 0
eg = 80

[[psts]]
mg = -21
eg = 121

[[psts]]
mg = -11
eg = 142

[[psts]]
mg = -14
eg = 144

[[psts]]
mg = -4
eg = 135

[[psts]]
mg = -6
eg = 133

[[psts]]
mg = 6
eg = 134

[[psts]]
mg = 26
eg = 131

[[psts]]
mg = 4
eg = 115

[[psts]]
mg = 4
eg = 144

[[psts]]
mg = 22
eg = 143

[[psts]]
mg = 33
eg = 148

[[psts]]
mg = 62
eg = 137

[[psts]]
mg = 47
eg = 139

[[psts]]
mg = 65
eg = 133

[[psts]]
mg = 65
eg = 129

[[psts]]
mg = 50
eg = 132

[[psts]]
mg = 8
eg = 158

[[psts]]
mg = 66
eg = 136

[[psts]]
mg = 52
eg = 153

[[psts]]
mg = 86
eg = 136

[[psts]]
mg = 110
eg = 126

[[psts]]
mg = 117
eg = 135

[[psts]]
mg = 150
eg = 108

[[psts]]
mg = 64
eg = 140

[[psts]]
mg = 40
eg = 164

[[psts]]
mg = 30
eg = 174

[[psts]]
mg = 69
eg = 168

[[psts]]
mg = 99
eg = 167

[[psts]]
mg = 92
eg = 171

[[psts]]
mg = 139
eg = 139

[[psts]]
mg = 73
eg = 157

[[psts]]
mg = 87
eg = 148

[[psts]]
mg = 98
eg = 153

[[psts]]
mg = 93
eg = 158

[[psts]]
mg = 75
eg = 166

[[psts]]
mg = 90
eg = 160

[[psts]]
mg = 98
eg = 162

[[psts]]
mg = 114
eg = 166

[[psts]]
mg = 135
eg = 159

[[psts]]
mg = 156
eg = 151

[[psts]]
mg = 22
eg = 39

[[psts]]
mg = 33
eg = 14

[[psts]]
mg = 41
eg = 5

[[psts]]
mg = 44
eg = 42

[[psts]]
mg = 43
eg = 22

[[psts]]
mg = 34
eg = 3

[[psts]]
mg = 45
eg = -12

[[psts]]
mg = 16
eg = -2

[[psts]]
mg = 16
eg = 42

[[psts]]
mg = 31
eg = 49

[[psts]]
mg = 42
eg = 23

[[psts]]
mg = 34
eg = 67

[[psts]]
mg = 37
eg = 59

[[psts]]
mg = 52
eg = 2

[[psts]]
mg = 44
eg = 2

[[psts]]
mg = 6
eg = 35

[[psts]]
mg = 19
eg = 70

[[psts]]
mg = 34
eg = 94

[[psts]]
mg = 28
eg = 124

[[psts]]
mg = 19
eg = 104

[[psts]]
mg = 23
eg = 104

[[psts]]
mg = 27
eg = 139

[[psts]]
mg = 50
eg = 99

[[psts]]
mg = 39
eg = 74

[[psts]]
mg = 15
eg = 108

[[psts]]
mg = 19
eg = 150

[[psts]]
mg = 10
eg = 156

[[psts]]
mg = -2
eg = 209

[[psts]]
mg = 0
eg = 202

[[psts]]
mg = 15
eg = 203

[[psts]]
mg = 28
eg = 172

[[psts]]
mg = 31
eg = 187

[[psts]]
mg = 12
eg = 136

[[psts]]
mg = 8
eg = 184

[[psts]]
mg = 3
eg = 182

[[psts]]
mg = -5
eg = 237

[[psts]]
mg = -4
eg = 267

[[psts]]
mg = 13
eg = 274

[[psts]]
mg = 32
eg = 265

[[psts]]
mg = 43
eg = 230

[[psts]]
mg = 6
eg = 150

[[psts]]
mg = 5
eg = 158

[[psts]]
mg = -7
eg = 212

[[psts]]
mg = 6
eg = 239

[[psts]]
mg = 28
eg = 264

[[psts]]
mg = 54
eg = 297

[[psts]]
mg = 92
eg = 230

[[psts]]
mg = 59
eg = 260

[[psts]]
mg = -3
eg = 174

[[psts]]
mg = -69
eg = 240

[[psts]]
mg = -10
eg = 237

[[psts]]
mg = -42
eg = 300

[[psts]]
mg = -20
eg = 336

[[psts]]
mg = 41
eg = 300

[[psts]]
mg = -62
eg = 307

[[psts]]
mg = 5
eg = 236

[[psts]]
mg = 25
eg = 186

[[psts]]
mg = 17
eg = 226

[[psts]]
mg = 21
eg = 242

[[psts]]
mg = 48
eg = 249

[[psts]]
mg = 55
eg = 271

[[psts]]
mg = 71
eg = 275

[[psts]]
mg = 41
eg = 271

[[psts]]
mg = 81
eg = 232

[[psts]]
mg = 0
eg = -117

[[psts]]
mg = 26
eg = -57

[[psts]]
mg = -17
eg = -24

[[psts]]
mg = -92
eg = -32

[[psts]]
mg = -36
eg = -78

[[psts]]
mg = -105
eg = -15

[[psts]]
mg = 26
eg = -64

[[psts]]
mg = 32
eg = -154

[[psts]]
mg = 16
eg = -32

[[psts]]
mg = -14
eg = 0

[[psts]]
mg = -42
eg = 25

[[psts]]
mg = -124
eg = 48

[[psts]]
mg = -87
eg = 34

[[psts]]
mg = -89
eg = 30

[[psts]]
mg = -2
eg = -15

[[psts]]
mg = 18
eg = -58

[[psts]]
mg = -78
eg = -9

[[psts]]
mg = -34
eg = 24

[[psts]]
mg = -31
eg = 49

[[psts]]
mg = -63
eg = 77

[[psts]]
mg = -40
eg = 67

[[psts]]
mg = -42
eg = 47

[[psts]]
mg = -19
eg = 10

[[psts]]
mg = -61
eg = -20

[[psts]]
mg = -69
eg = -18

[[psts]]
mg = 34
eg = 38

[[psts]]
mg = 53
eg = 68

[[psts]]
mg = -13
eg = 99

[[psts]]
mg = 10
eg = 89

[[psts]]
mg = 14
eg = 64

[[psts]]
mg = 36
eg = 29

[[psts]]
mg = -80
eg = -18

[[psts]]
mg = -52
eg = 18

[[psts]]
mg = 96
eg = 58

[[psts]]
mg = 122
eg = 79

[[psts]]
mg = 56
eg = 93

[[psts]]
mg = 79
eg = 83

[[psts]]
mg = 105
eg = 71

[[psts]]
mg = 77
eg = 53

[[psts]]
mg = -89
eg = 8

[[psts]]
mg = -2
eg = 15

[[psts]]
mg = 181
eg = 66

[[psts]]
mg = 229
eg = 60

[[psts]]
mg = 187
eg = 51

[[psts]]
mg = 189
eg = 42

[[psts]]
mg = 224
eg = 61

[[psts]]
mg = 159
eg = 65

[[psts]]
mg = -10
eg = 1

[[psts]]
mg = 1
eg = -59

[[psts]]
mg = 162
eg = 48

[[psts]]
mg = 231
eg = 26

[[psts]]
mg = 229
eg = 2

[[psts]]
mg = 176
eg = 11

[[psts]]
mg = 225
eg = 21

[[psts]]
mg = 102
eg = 61

[[psts]]
mg = 42
eg = -63

[[psts]]
mg = 275
eg = -310

[[psts]]
mg = 400
eg = -140

[[psts]]
mg = 322
eg = -88

[[psts]]
mg = 277
eg = -48

[[psts]]
mg = 301
eg = -80

[[psts]]
mg = 235
eg = -66

[[psts]]
mg = 295
eg = -83

[[psts]]
mg = 164
eg = -271
