[[material]]
mg = 100
eg = 174

[[material]]
mg = 362
eg = 553

[[material]]
mg = 384
eg = 563

[[material]]
mg = 528
eg = 1042

[[material]]
mg = 1296
eg = 1973

[bishop_pair_bonus]
mg = 20
eg = 116

[castling_bonus]
mg = 8
eg = 0

[pawn_shield_full]
mg = 22
eg = -8

[pawn_shield_partial]
mg = 13
eg = -4

[open_file_penalty]
mg = -47
eg = -14

[semi_open_file_penalty]
mg = -41
eg = 26

[potential_open_file_penalty]
mg = -12
eg = 0

[isolated_penalty]
mg = -13
eg = -21

[doubled_penalty]
mg = -1
eg = -16

[backward_penalty]
mg = -10
eg = -18

[[passed_pawn_scores]]
mg = 0
eg = 0

[[passed_pawn_scores]]
mg = -10
eg = 25

[[passed_pawn_scores]]
mg = -22
eg = 30

[[passed_pawn_scores]]
mg = -13
eg = 67

[[passed_pawn_scores]]
mg = 20
eg = 97

[[passed_pawn_scores]]
mg = 42
eg = 190

[[passed_pawn_scores]]
mg = 151
eg = 258

[[passed_pawn_scores]]
mg = 0
eg = 0

[connected_bonus]
mg = 0
eg = 5

[rook_open_file_bonus]
mg = 47
eg = 17

[rook_semi_file_bonus]
mg = 18
eg = 17

[knight_outpost_bonus]
mg = 2
eg = 45

[tempo_bonus]
mg = 14
eg = 18

[[mobility_knight]]
mg = 16
eg = -8

[[mobility_knight]]
mg = 19
eg = 35

[[mobility_knight]]
mg = 21
eg = 45

[[mobility_knight]]
mg = 23
eg = 54

[[mobility_knight]]
mg = 23
eg = 60

[[mobility_knight]]
mg = 22
eg = 63

[[mobility_knight]]
mg = 20
eg = 63

[[mobility_knight]]
mg = 20
eg = 60

[[mobility_knight]]
mg = 19
eg = 53

[[mobility_bishop]]
mg = -3
eg = -132

[[mobility_bishop]]
mg = 3
eg = -39

[[mobility_bishop]]
mg = 11
eg = -5

[[mobility_bishop]]
mg = 12
eg = 19

[[mobility_bishop]]
mg = 18
eg = 42

[[mobility_bishop]]
mg = 26
eg = 60

[[mobility_bishop]]
mg = 32
eg = 75

[[mobility_bishop]]
mg = 33
eg = 87

[[mobility_bishop]]
mg = 33
eg = 97

[[mobility_bishop]]
mg = 35
eg = 97

[[mobility_bishop]]
mg = 37
eg = 95

[[mobility_bishop]]
mg = 45
eg = 92

[[mobility_bishop]]
mg = 42
eg = 92

[[mobility_bishop]]
mg = 111
eg = 62

[[mobility_rook]]
mg = -7
eg = -55

[[mobility_rook]]
mg = -4
eg = -29

[[mobility_rook]]
mg = 0
eg = -3

[[mobility_rook]]
mg = 3
eg = 17

[[mobility_rook]]
mg = 3
eg = 34

[[mobility_rook]]
mg = 7
eg = 42

[[mobility_rook]]
mg = 11
eg = 50

[[mobility_rook]]
mg = 16
eg = 52

[[mobility_rook]]
mg = 17
eg = 61

[[mobility_rook]]
mg = 19
eg = 70

[[mobility_rook]]
mg = 24
eg = 73

[[mobility_rook]]
mg = 25
eg = 76

[[mobility_rook]]
mg = 28
eg = 77

[[mobility_rook]]
mg = 46
eg = 69

[[mobility_rook]]
mg = 64
eg = 50

[[mobility_queen]]
mg = -27
eg = -499

[[mobility_queen]]
mg = -14
eg = -419

[[mobility_queen]]
mg = -3
eg = -213

[[mobility_queen]]
mg = 0
eg = -104

[[mobility_queen]]
mg = 1
eg = -50

[[mobility_queen]]
mg = 1
eg = -15

[[mobility_queen]]
mg = 4
eg = 7

[[mobility_queen]]
mg = 4
eg = 38

[[mobility_queen]]
mg = 7
eg = 49

[[mobility_queen]]
mg = 11
eg = 60

[[mobility_queen]]
mg = 14
eg = 70

[[mobility_queen]]
mg = 16
eg = 81

[[mobility_queen]]
mg = 18
eg = 88

[[mobility_queen]]
mg = 21
eg = 93

[[mobility_queen]]
mg = 23
eg = 99

[[mobility_queen]]
mg = 23
eg = 104

[[mobility_queen]]
mg = 21
eg = 112

[[mobility_queen]]
mg = 23
eg = 112

[[mobility_queen]]
mg = 25
eg = 111

[[mobility_queen]]
mg = 22
eg = 114

[[mobility_queen]]
mg = 15
eg = 122

[[mobility_queen]]
mg = 26
eg = 107

[[mobility_queen]]
mg = 21
eg = 107

[[mobility_queen]]
mg = 28
eg = 95

[[mobility_queen]]
mg = 12
eg = 101

[[mobility_queen]]
mg = 0
eg = 98

[[mobility_queen]]
mg = -67
eg = 122

[[mobility_queen]]
mg = 26
eg = 109

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -9
eg = 33

[[psts]]
mg = -6
eg = 31

[[psts]]
mg = -9
eg = 44

[[psts]]
mg = -10
eg = 44

[[psts]]
mg = -8
eg = 48

[[psts]]
mg = 11
eg = 56

[[psts]]
mg = 20
eg = 29

[[psts]]
mg = -16
eg = 14

[[psts]]
mg = -3
eg = 25

[[psts]]
mg = -1
eg = 24

[[psts]]
mg = 1
eg = 28

[[psts]]
mg = 5
eg = 24

[[psts]]
mg = 18
eg = 30

[[psts]]
mg = 4
eg = 40

[[psts]]
mg = 14
eg = 26

[[psts]]
mg = -8
eg = 18

[[psts]]
mg = -2
eg = 36

[[psts]]
mg = 3
eg = 36

[[psts]]
mg = 14
eg = 20

[[psts]]
mg = 23
eg = 16

[[psts]]
mg = 33
eg = 16

[[psts]]
mg = 16
eg = 30

[[psts]]
mg = 6
eg = 32

[[psts]]
mg = -14
eg = 28

[[psts]]
mg = 11
eg = 65

[[psts]]
mg = 24
eg = 56

[[psts]]
mg = 29
eg = 38

[[psts]]
mg = 50
eg = 9

[[psts]]
mg = 65
eg = 13

[[psts]]
mg = 50
eg = 29

[[psts]]
mg = 23
eg = 51

[[psts]]
mg = -2
eg = 50

[[psts]]
mg = 8
eg = 108

[[psts]]
mg = 52
eg = 92

[[psts]]
mg = 80
eg = 51

[[psts]]
mg = 78
eg = 5

[[psts]]
mg = 97
eg = -2

[[psts]]
mg = 130
eg = 30

[[psts]]
mg = 66
eg = 67

[[psts]]
mg = 0
eg = 83

[[psts]]
mg = 84
eg = 94

[[psts]]
mg = 57
eg = 99

[[psts]]
mg = 97
eg = 49

[[psts]]
mg = 113
eg = -1

[[psts]]
mg = 111
eg = -8

[[psts]]
mg = 55
eg = 26

[[psts]]
mg = -115
eg = 109

[[psts]]
mg = -86
eg = 107

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -62
eg = -47

[[psts]]
mg = -14
eg = -25

[[psts]]
mg = -15
eg = 14

[[psts]]
mg = -19
eg = 40

[[psts]]
mg = -9
eg = 42

[[psts]]
mg = -2
eg = 26

[[psts]]
mg = -9
eg = -10

[[psts]]
mg = -55
eg = -63

[[psts]]
mg = -27
eg = 16

[[psts]]
mg = -33
eg = 50

[[psts]]
mg = 2
eg = 47

[[psts]]
mg = 18
eg = 68

[[psts]]
mg = 12
eg = 74

[[psts]]
mg = 14
eg = 45

[[psts]]
mg = -9
eg = 43

[[psts]]
mg = 1
eg = 17

[[psts]]
mg = -11
eg = 0

[[psts]]
mg = 20
eg = 57

[[psts]]
mg = 32
eg = 91

[[psts]]
mg = 44
eg = 111

[[psts]]
mg = 49
eg = 109

[[psts]]
mg = 44
eg = 92

[[psts]]
mg = 33
eg = 64

[[psts]]
mg = 8
eg = 4

[[psts]]
mg = 7
eg = 45

[[psts]]
mg = 34
eg = 79

[[psts]]
mg = 49
eg = 112

[[psts]]
mg = 50
eg = 124

[[psts]]
mg = 60
eg = 127

[[psts]]
mg = 46
eg = 113

[[psts]]
mg = 63
eg = 79

[[psts]]
mg = 24
eg = 53

[[psts]]
mg = 21
eg = 46

[[psts]]
mg = 46
eg = 77

[[psts]]
mg = 81
eg = 116

[[psts]]
mg = 88
eg = 135

[[psts]]
mg = 73
eg = 139

[[psts]]
mg = 101
eg = 115

[[psts]]
mg = 63
eg = 92

[[psts]]
mg = 41
eg = 57

[[psts]]
mg = 3
eg = 29

[[psts]]
mg = 49
eg = 67

[[psts]]
mg = 101
eg = 109

[[psts]]
mg = 116
eg = 110

[[psts]]
mg = 161
eg = 95

[[psts]]
mg = 148
eg = 104

[[psts]]
mg = 100
eg = 60

[[psts]]
mg = 34
eg = 35

[[psts]]
mg = -3
eg = 7

[[psts]]
mg = 0
eg = 47

[[psts]]
mg = 72
eg = 63

[[psts]]
mg = 123
eg = 90

[[psts]]
mg = 103
eg = 90

[[psts]]
mg = 134
eg = 45

[[psts]]
mg = -10
eg = 44

[[psts]]
mg = 22
eg = 7

[[psts]]
mg = -240
eg = -55

[[psts]]
mg = -116
eg = 40

[[psts]]
mg = -132
eg = 95

[[psts]]
mg = 2
eg = 61

[[psts]]
mg = 49
eg = 54

[[psts]]
mg = -118
eg = 98

[[psts]]
mg = -138
eg = 61

[[psts]]
mg = -172
eg = -88

[[psts]]
mg = 37
eg = 41

[[psts]]
mg = 18
eg = 60

[[psts]]
mg = 7
eg = 60

[[psts]]
mg = 6
eg = 62

[[psts]]
mg = 0
eg = 68

[[psts]]
mg = 16
eg = 67

[[psts]]
mg = 11
eg = 65

[[psts]]
mg = 28
eg = 38

[[psts]]
mg = 32
eg = 45

[[psts]]
mg = 37
eg = 45

[[psts]]
mg = 33
eg = 58

[[psts]]
mg = 16
eg = 69

[[psts]]
mg = 25
eg = 67

[[psts]]
mg = 31
eg = 59

[[psts]]
mg = 51
eg = 55

[[psts]]
mg = 34
eg = 19

[[psts]]
mg = 19
eg = 62

[[psts]]
mg = 43
eg = 80

[[psts]]
mg = 32
eg = 86

[[psts]]
mg = 37
eg = 88

[[psts]]
mg = 30
eg = 89

[[psts]]
mg = 39
eg = 82

[[psts]]
mg = 44
eg = 76

[[psts]]
mg = 42
eg = 66

[[psts]]
mg = 13
eg = 65

[[psts]]
mg = 25
eg = 82

[[psts]]
mg = 34
eg = 103

[[psts]]
mg = 48
eg = 104

[[psts]]
mg = 52
eg = 103

[[psts]]
mg = 22
eg = 101

[[psts]]
mg = 31
eg = 81

[[psts]]
mg = 17
eg = 65

[[psts]]
mg = 4
eg = 80

[[psts]]
mg = 44
eg = 96

[[psts]]
mg = 42
eg = 95

[[psts]]
mg = 85
eg = 104

[[psts]]
mg = 63
eg = 114

[[psts]]
mg = 55
eg = 96

[[psts]]
mg = 36
eg = 104

[[psts]]
mg = 16
eg = 86

[[psts]]
mg = 19
eg = 82

[[psts]]
mg = 38
eg = 101

[[psts]]
mg = 67
eg = 93

[[psts]]
mg = 59
eg = 90

[[psts]]
mg = 91
eg = 88

[[psts]]
mg = 77
eg = 102

[[psts]]
mg = 73
eg = 97

[[psts]]
mg = 30
eg = 87

[[psts]]
mg = -46
eg = 86

[[psts]]
mg = 12
eg = 95

[[psts]]
mg = 8
eg = 96

[[psts]]
mg = -12
eg = 97

[[psts]]
mg = 11
eg = 91

[[psts]]
mg = 32
eg = 94

[[psts]]
mg = 4
eg = 97

[[psts]]
mg = -3
eg = 74

[[psts]]
mg = -53
eg = 105

[[psts]]
mg = -76
eg = 112

[[psts]]
mg = -137
eg = 114

[[psts]]
mg = -125
eg = 119

[[psts]]
mg = -92
eg = 114

[[psts]]
mg = -142
eg = 111

[[psts]]
mg = -10
eg = 94

[[psts]]
mg = -39
eg = 101

[[psts]]
mg = 4
eg = 68

[[psts]]
mg = 13
eg = 79

[[psts]]
mg = 21
eg = 83

[[psts]]
mg = 32
eg = 73

[[psts]]
mg = 28
eg = 74

[[psts]]
mg = 33
eg = 86

[[psts]]
mg = 34
eg = 72

[[psts]]
mg = 21
eg = 51

[[psts]]
mg = -74
eg = 74

[[psts]]
mg = -9
eg = 61

[[psts]]
mg = -3
eg = 73

[[psts]]
mg = 3
eg = 68

[[psts]]
mg = 4
eg = 68

[[psts]]
mg = 25
eg = 57

[[psts]]
mg = 27
eg = 51

[[psts]]
mg = -64
eg = 72

[[psts]]
mg = -29
eg = 71

[[psts]]
mg = 0
eg = 89

[[psts]]
mg = -12
eg = 88

[[psts]]
mg = -4
eg = 81

[[psts]]
mg = -3
eg = 81

[[psts]]
mg = 4
eg = 85

[[psts]]
mg = 39
eg = 79

[[psts]]
mg = -1
eg = 63

[[psts]]
mg = -20
eg = 100

[[psts]]
mg = -12
eg = 120

[[psts]]
mg = -14
eg = 121

[[psts]]
mg = -4
eg = 112

[[psts]]
mg = -6
eg = 110

[[psts]]
mg = 5
eg = 111

[[psts]]
mg = 25
eg = 109

[[psts]]
mg = 4
eg = 94

[[psts]]
mg = 2
eg = 122

[[psts]]
mg = 18
eg = 121

[[psts]]
mg = 28
eg = 126

[[psts]]
mg = 56
eg = 115

[[psts]]
mg = 42
eg = 116

[[psts]]
mg = 60
eg = 110

[[psts]]
mg = 61
eg = 106

[[psts]]
mg = 46
eg = 110

[[psts]]
mg = 5
eg = 135

[[psts]]
mg = 58
eg = 115

[[psts]]
mg = 44
eg = 130

[[psts]]
mg = 76
eg = 115

[[psts]]
mg = 101
eg = 105

[[psts]]
mg = 106
eg = 113

[[psts]]
mg = 139
eg = 87

[[psts]]
mg = 58
eg = 118

[[psts]]
mg = 34
eg = 142

[[psts]]
mg = 24
eg = 151

[[psts]]
mg = 60
eg = 146

[[psts]]
mg = 88
eg = 145

[[psts]]
mg = 82
eg = 148

[[psts]]
mg = 126
eg = 118

[[psts]]
mg = 66
eg = 134

[[psts]]
mg = 79
eg = 127

[[psts]]
mg = 85
eg = 137

[[psts]]
mg = 78
eg = 144

[[psts]]
mg = 58
eg = 153

[[psts]]
mg = 71
eg = 147

[[psts]]
mg = 81
eg = 147

[[psts]]
mg = 100
eg = 147

[[psts]]
mg = 123
eg = 139

[[psts]]
mg = 142
eg = 132

[[psts]]
mg = 19
eg = 44

[[psts]]
mg = 27
eg = 19

[[psts]]
mg = 33
eg = 11

[[psts]]
mg = 37
eg = 52

[[psts]]
mg = 36
eg = 25

[[psts]]
mg = 28
eg = 6

[[psts]]
mg = 38
eg = -4

[[psts]]
mg = 14
eg = 23

[[psts]]
mg = 13
eg = 39

[[psts]]
mg = 27
eg = 44

[[psts]]
mg = 37
eg = 18

[[psts]]
mg = 29
eg = 60

[[psts]]
mg = 33
eg = 52

[[psts]]
mg = 46
eg = 0

[[psts]]
mg = 39
eg = 0

[[psts]]
mg = 2
eg = 37

[[psts]]
mg = 16
eg = 59

[[psts]]
mg = 31
eg = 78

[[psts]]
mg = 24
eg = 114

[[psts]]
mg = 16
eg = 94

[[psts]]
mg = 20
eg = 94

[[psts]]
mg = 23
eg = 126

[[psts]]
mg = 46
eg = 84

[[psts]]
mg = 35
eg = 63

[[psts]]
mg = 12
eg = 91

[[psts]]
mg = 16
eg = 135

[[psts]]
mg = 8
eg = 144

[[psts]]
mg = -4
eg = 203

[[psts]]
mg = 0
eg = 195

[[psts]]
mg = 14
eg = 186

[[psts]]
mg = 25
eg = 152

[[psts]]
mg = 28
eg = 164

[[psts]]
mg = 9
eg = 118

[[psts]]
mg = 6
eg = 168

[[psts]]
mg = 4
eg = 170

[[psts]]
mg = -4
eg = 232

[[psts]]
mg = -4
eg = 260

[[psts]]
mg = 14
eg = 256

[[psts]]
mg = 30
eg = 239

[[psts]]
mg = 38
eg = 206

[[psts]]
mg = 1
eg = 134

[[psts]]
mg = 2
eg = 142

[[psts]]
mg = -7
eg = 198

[[psts]]
mg = 8
eg = 223

[[psts]]
mg = 29
eg = 249

[[psts]]
mg = 50
eg = 276

[[psts]]
mg = 85
eg = 207

[[psts]]
mg = 52
eg = 237

[[psts]]
mg = -7
eg = 155

[[psts]]
mg = -68
eg = 218

[[psts]]
mg = -10
eg = 217

[[psts]]
mg = -39
eg = 277

[[psts]]
mg = -19
eg = 310

[[psts]]
mg = 38
eg = 273

[[psts]]
mg = -61
eg = 281

[[psts]]
mg = 1
eg = 213

[[psts]]
mg = 21
eg = 167

[[psts]]
mg = 13
eg = 204

[[psts]]
mg = 17
eg = 221

[[psts]]
mg = 41
eg = 230

[[psts]]
mg = 48
eg = 248

[[psts]]
mg = 64
eg = 249

[[psts]]
mg = 37
eg = 245

[[psts]]
mg = 74
eg = 210

[[psts]]
mg = 1
eg = -112

[[psts]]
mg = 25
eg = -56

[[psts]]
mg = -15
eg = -24

[[psts]]
mg = -85
eg = -31

[[psts]]
mg = -32
eg = -73

[[psts]]
mg = -96
eg = -16

[[psts]]
mg = 26
eg = -62

[[psts]]
mg = 31
eg = -147

[[psts]]
mg = 17
eg = -31

[[psts]]
mg = -12
eg = 0

[[psts]]
mg = -39
eg = 22

[[psts]]
mg = -117
eg = 45

[[psts]]
mg = -82
eg = 31

[[psts]]
mg = -83
eg = 27

[[psts]]
mg = -1
eg = -15

[[psts]]
mg = 18
eg = -56

[[psts]]
mg = -73
eg = -9

[[psts]]
mg = -31
eg = 21

[[psts]]
mg = -29
eg = 46

[[psts]]
mg = -61
eg = 72

[[psts]]
mg = -40
eg = 63

[[psts]]
mg = -39
eg = 44

[[psts]]
mg = -18
eg = 9

[[psts]]
mg = -56
eg = -20

[[psts]]
mg = -66
eg = -17

[[psts]]
mg = 32
eg = 36

[[psts]]
mg = 48
eg = 64

[[psts]]
mg = -13
eg = 94

[[psts]]
mg = 8
eg = 84

[[psts]]
mg = 12
eg = 61

[[psts]]
mg = 34
eg = 27

[[psts]]
mg = -76
eg = -18

[[psts]]
mg = -52
eg = 16

[[psts]]
mg = 89
eg = 54

[[psts]]
mg = 114
eg = 74

[[psts]]
mg = 53
eg = 87

[[psts]]
mg = 74
eg = 78

[[psts]]
mg = 99
eg = 67

[[psts]]
mg = 71
eg = 50

[[psts]]
mg = -85
eg = 7

[[psts]]
mg = -4
eg = 14

[[psts]]
mg = 169
eg = 62

[[psts]]
mg = 212
eg = 57

[[psts]]
mg = 174
eg = 48

[[psts]]
mg = 177
eg = 40

[[psts]]
mg = 209
eg = 57

[[psts]]
mg = 148
eg = 61

[[psts]]
mg = -13
eg = 0

[[psts]]
mg = -6
eg = -55

[[psts]]
mg = 144
eg = 45

[[psts]]
mg = 210
eg = 25

[[psts]]
mg = 209
eg = 3

[[psts]]
mg = 158
eg = 11

[[psts]]
mg = 206
eg = 19

[[psts]]
mg = 89
eg = 57

[[psts]]
mg = 32
eg = -59

[[psts]]
mg = 247
eg = -290

[[psts]]
mg = 364
eg = -132

[[psts]]
mg = 294
eg = -83

[[psts]]
mg = 251
eg = -45

[[psts]]
mg = 274
eg = -76

[[psts]]
mg = 209
eg = -62

[[psts]]
mg = 266
eg = -78

[[psts]]
mg = 145
eg = -253
