[[material]]
mg = 146
eg = 243

[[material]]
mg = 683
eg = 936

[[material]]
mg = 674
eg = 875

[[material]]
mg = 905
eg = 1593

[[material]]
mg = 2278
eg = 3010

[bishop_pair_bonus]
mg = 41
eg = 181

[castling_bonus]
mg = 30
eg = 0

[pawn_shield_full]
mg = 37
eg = -25

[pawn_shield_partial]
mg = 30
eg = -16

[open_file_penalty]
mg = -82
eg = -19

[semi_open_file_penalty]
mg = -78
eg = 43

[isolated_penalty]
mg = -23
eg = -29

[doubled_penalty]
mg = 0
eg = -26

[backward_penalty]
mg = -15
eg = -30

[[passed_pawn_scores]]
mg = 0
eg = 0

[[passed_pawn_scores]]
mg = -15
eg = 37

[[passed_pawn_scores]]
mg = -41
eg = 49

[[passed_pawn_scores]]
mg = -24
eg = 109

[[passed_pawn_scores]]
mg = 26
eg = 154

[[passed_pawn_scores]]
mg = 43
eg = 305

[[passed_pawn_scores]]
mg = 278
eg = 460

[[passed_pawn_scores]]
mg = 0
eg = 0

[connected_bonus]
mg = 1
eg = 10

[rook_open_file_bonus]
mg = 77
eg = 17

[rook_semi_file_bonus]
mg = 24
eg = 32

[knight_outpost_bonus]
mg = -3
eg = 70

[[mobility]]
mg = 1
eg = 2

[[mobility]]
mg = -1
eg = 0

[[mobility]]
mg = 11
eg = 17

[[mobility]]
mg = 7
eg = 7

[[mobility]]
mg = 8
eg = 4

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -2
eg = 68

[[psts]]
mg = 15
eg = 76

[[psts]]
mg = 12
eg = 109

[[psts]]
mg = 13
eg = 98

[[psts]]
mg = 18
eg = 90

[[psts]]
mg = 15
eg = 114

[[psts]]
mg = 27
eg = 75

[[psts]]
mg = -7
eg = 60

[[psts]]
mg = 0
eg = 60

[[psts]]
mg = 25
eg = 66

[[psts]]
mg = 20
eg = 79

[[psts]]
mg = 35
eg = 64

[[psts]]
mg = 54
eg = 60

[[psts]]
mg = 20
eg = 83

[[psts]]
mg = 29
eg = 70

[[psts]]
mg = -8
eg = 61

[[psts]]
mg = 8
eg = 74

[[psts]]
mg = 18
eg = 83

[[psts]]
mg = 40
eg = 66

[[psts]]
mg = 70
eg = 47

[[psts]]
mg = 80
eg = 41

[[psts]]
mg = 46
eg = 70

[[psts]]
mg = 18
eg = 82

[[psts]]
mg = -5
eg = 76

[[psts]]
mg = 43
eg = 115

[[psts]]
mg = 59
eg = 117

[[psts]]
mg = 84
eg = 84

[[psts]]
mg = 122
eg = 47

[[psts]]
mg = 130
eg = 42

[[psts]]
mg = 89
eg = 78

[[psts]]
mg = 53
eg = 116

[[psts]]
mg = 25
eg = 114

[[psts]]
mg = 35
eg = 175

[[psts]]
mg = 149
eg = 160

[[psts]]
mg = 188
eg = 97

[[psts]]
mg = 181
eg = 37

[[psts]]
mg = 203
eg = 26

[[psts]]
mg = 208
eg = 82

[[psts]]
mg = 153
eg = 149

[[psts]]
mg = 25
eg = 176

[[psts]]
mg = 60
eg = 101

[[psts]]
mg = -12
eg = 143

[[psts]]
mg = 120
eg = 36

[[psts]]
mg = 142
eg = -27

[[psts]]
mg = 168
eg = -36

[[psts]]
mg = 108
eg = 22

[[psts]]
mg = -75
eg = 139

[[psts]]
mg = -81
eg = 136

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = 0
eg = 0

[[psts]]
mg = -98
eg = -105

[[psts]]
mg = -23
eg = -55

[[psts]]
mg = -8
eg = 6

[[psts]]
mg = -19
eg = 35

[[psts]]
mg = -15
eg = 41

[[psts]]
mg = -8
eg = 17

[[psts]]
mg = -22
eg = -27

[[psts]]
mg = -93
eg = -130

[[psts]]
mg = -12
eg = 20

[[psts]]
mg = -49
eg = 70

[[psts]]
mg = 16
eg = 76

[[psts]]
mg = 37
eg = 109

[[psts]]
mg = 35
eg = 113

[[psts]]
mg = 19
eg = 77

[[psts]]
mg = -23
eg = 57

[[psts]]
mg = -7
eg = 11

[[psts]]
mg = -20
eg = 24

[[psts]]
mg = 39
eg = 89

[[psts]]
mg = 76
eg = 141

[[psts]]
mg = 84
eg = 164

[[psts]]
mg = 84
eg = 165

[[psts]]
mg = 78
eg = 150

[[psts]]
mg = 51
eg = 99

[[psts]]
mg = 4
eg = 12

[[psts]]
mg = 46
eg = 69

[[psts]]
mg = 80
eg = 121

[[psts]]
mg = 104
eg = 159

[[psts]]
mg = 113
eg = 180

[[psts]]
mg = 123
eg = 183

[[psts]]
mg = 105
eg = 161

[[psts]]
mg = 99
eg = 122

[[psts]]
mg = 50
eg = 65

[[psts]]
mg = 41
eg = 63

[[psts]]
mg = 112
eg = 129

[[psts]]
mg = 147
eg = 179

[[psts]]
mg = 167
eg = 196

[[psts]]
mg = 165
eg = 197

[[psts]]
mg = 169
eg = 163

[[psts]]
mg = 124
eg = 138

[[psts]]
mg = 51
eg = 65

[[psts]]
mg = 39
eg = 44

[[psts]]
mg = 172
eg = 87

[[psts]]
mg = 210
eg = 154

[[psts]]
mg = 233
eg = 154

[[psts]]
mg = 272
eg = 141

[[psts]]
mg = 234
eg = 151

[[psts]]
mg = 188
eg = 80

[[psts]]
mg = 36
eg = 57

[[psts]]
mg = -10
eg = -9

[[psts]]
mg = -6
eg = 70

[[psts]]
mg = 121
eg = 103

[[psts]]
mg = 235
eg = 115

[[psts]]
mg = 177
eg = 141

[[psts]]
mg = 189
eg = 103

[[psts]]
mg = -4
eg = 63

[[psts]]
mg = -4
eg = -6

[[psts]]
mg = -374
eg = -97

[[psts]]
mg = -234
eg = 63

[[psts]]
mg = -171
eg = 144

[[psts]]
mg = 12
eg = 100

[[psts]]
mg = 57
eg = 87

[[psts]]
mg = -203
eg = 153

[[psts]]
mg = -297
eg = 106

[[psts]]
mg = -333
eg = -171

[[psts]]
mg = 50
eg = 19

[[psts]]
mg = 25
eg = 43

[[psts]]
mg = 23
eg = 55

[[psts]]
mg = 14
eg = 61

[[psts]]
mg = 7
eg = 69

[[psts]]
mg = 19
eg = 67

[[psts]]
mg = 19
eg = 57

[[psts]]
mg = 37
eg = 11

[[psts]]
mg = 44
eg = 29

[[psts]]
mg = 53
eg = 35

[[psts]]
mg = 46
eg = 66

[[psts]]
mg = 30
eg = 83

[[psts]]
mg = 32
eg = 87

[[psts]]
mg = 39
eg = 71

[[psts]]
mg = 63
eg = 44

[[psts]]
mg = 45
eg = 22

[[psts]]
mg = 32
eg = 75

[[psts]]
mg = 61
eg = 112

[[psts]]
mg = 47
eg = 104

[[psts]]
mg = 58
eg = 104

[[psts]]
mg = 45
eg = 105

[[psts]]
mg = 51
eg = 100

[[psts]]
mg = 60
eg = 106

[[psts]]
mg = 51
eg = 84

[[psts]]
mg = 19
eg = 84

[[psts]]
mg = 21
eg = 108

[[psts]]
mg = 64
eg = 128

[[psts]]
mg = 65
eg = 111

[[psts]]
mg = 71
eg = 115

[[psts]]
mg = 52
eg = 128

[[psts]]
mg = 35
eg = 109

[[psts]]
mg = -4
eg = 96

[[psts]]
mg = 13
eg = 112

[[psts]]
mg = 57
eg = 136

[[psts]]
mg = 49
eg = 117

[[psts]]
mg = 119
eg = 114

[[psts]]
mg = 119
eg = 118

[[psts]]
mg = 53
eg = 119

[[psts]]
mg = 46
eg = 140

[[psts]]
mg = 12
eg = 116

[[psts]]
mg = 36
eg = 120

[[psts]]
mg = 87
eg = 134

[[psts]]
mg = 96
eg = 115

[[psts]]
mg = 101
eg = 108

[[psts]]
mg = 123
eg = 108

[[psts]]
mg = 87
eg = 117

[[psts]]
mg = 87
eg = 129

[[psts]]
mg = 26
eg = 120

[[psts]]
mg = -79
eg = 99

[[psts]]
mg = -15
eg = 139

[[psts]]
mg = 7
eg = 138

[[psts]]
mg = -37
eg = 129

[[psts]]
mg = -1
eg = 118

[[psts]]
mg = 6
eg = 138

[[psts]]
mg = -2
eg = 127

[[psts]]
mg = -52
eg = 93

[[psts]]
mg = -95
eg = 155

[[psts]]
mg = -137
eg = 153

[[psts]]
mg = -214
eg = 161

[[psts]]
mg = -206
eg = 163

[[psts]]
mg = -184
eg = 175

[[psts]]
mg = -273
eg = 165

[[psts]]
mg = -95
eg = 145

[[psts]]
mg = -57
eg = 133

[[psts]]
mg = 3
eg = 129

[[psts]]
mg = 42
eg = 148

[[psts]]
mg = 62
eg = 151

[[psts]]
mg = 74
eg = 144

[[psts]]
mg = 66
eg = 142

[[psts]]
mg = 69
eg = 158

[[psts]]
mg = 65
eg = 143

[[psts]]
mg = 32
eg = 125

[[psts]]
mg = -195
eg = 156

[[psts]]
mg = -2
eg = 126

[[psts]]
mg = 24
eg = 143

[[psts]]
mg = 29
eg = 140

[[psts]]
mg = 25
eg = 141

[[psts]]
mg = 41
eg = 132

[[psts]]
mg = 31
eg = 115

[[psts]]
mg = -142
eg = 142

[[psts]]
mg = -44
eg = 134

[[psts]]
mg = 35
eg = 162

[[psts]]
mg = 15
eg = 161

[[psts]]
mg = 8
eg = 159

[[psts]]
mg = 6
eg = 160

[[psts]]
mg = 11
eg = 166

[[psts]]
mg = 59
eg = 161

[[psts]]
mg = -9
eg = 128

[[psts]]
mg = -31
eg = 185

[[psts]]
mg = 13
eg = 209

[[psts]]
mg = 2
eg = 211

[[psts]]
mg = 7
eg = 205

[[psts]]
mg = -6
eg = 207

[[psts]]
mg = 7
eg = 213

[[psts]]
mg = 29
eg = 208

[[psts]]
mg = -5
eg = 185

[[psts]]
mg = 28
eg = 219

[[psts]]
mg = 62
eg = 209

[[psts]]
mg = 81
eg = 218

[[psts]]
mg = 108
eg = 203

[[psts]]
mg = 95
eg = 209

[[psts]]
mg = 85
eg = 211

[[psts]]
mg = 94
eg = 206

[[psts]]
mg = 66
eg = 210

[[psts]]
mg = 43
eg = 239

[[psts]]
mg = 145
eg = 195

[[psts]]
mg = 111
eg = 224

[[psts]]
mg = 156
eg = 207

[[psts]]
mg = 158
eg = 201

[[psts]]
mg = 145
eg = 215

[[psts]]
mg = 184
eg = 181

[[psts]]
mg = 72
eg = 231

[[psts]]
mg = 74
eg = 249

[[psts]]
mg = 84
eg = 257

[[psts]]
mg = 124
eg = 253

[[psts]]
mg = 152
eg = 251

[[psts]]
mg = 135
eg = 260

[[psts]]
mg = 164
eg = 245

[[psts]]
mg = 91
eg = 257

[[psts]]
mg = 93
eg = 243

[[psts]]
mg = 187
eg = 229

[[psts]]
mg = 157
eg = 242

[[psts]]
mg = 151
eg = 250

[[psts]]
mg = 163
eg = 246

[[psts]]
mg = 159
eg = 250

[[psts]]
mg = 151
eg = 255

[[psts]]
mg = 177
eg = 244

[[psts]]
mg = 213
eg = 226

[[psts]]
mg = 53
eg = 29

[[psts]]
mg = 81
eg = 8

[[psts]]
mg = 86
eg = 19

[[psts]]
mg = 94
eg = 41

[[psts]]
mg = 90
eg = 45

[[psts]]
mg = 89
eg = 2

[[psts]]
mg = 93
eg = 2

[[psts]]
mg = 48
eg = -9

[[psts]]
mg = 33
eg = 71

[[psts]]
mg = 69
eg = 50

[[psts]]
mg = 89
eg = 25

[[psts]]
mg = 73
eg = 106

[[psts]]
mg = 75
eg = 109

[[psts]]
mg = 87
eg = 38

[[psts]]
mg = 64
eg = 54

[[psts]]
mg = 17
eg = 57

[[psts]]
mg = 39
eg = 138

[[psts]]
mg = 70
eg = 153

[[psts]]
mg = 56
eg = 194

[[psts]]
mg = 53
eg = 166

[[psts]]
mg = 49
eg = 168

[[psts]]
mg = 53
eg = 207

[[psts]]
mg = 79
eg = 160

[[psts]]
mg = 63
eg = 110

[[psts]]
mg = 40
eg = 213

[[psts]]
mg = 41
eg = 267

[[psts]]
mg = 19
eg = 286

[[psts]]
mg = 3
eg = 332

[[psts]]
mg = 16
eg = 311

[[psts]]
mg = 16
eg = 309

[[psts]]
mg = 52
eg = 246

[[psts]]
mg = 50
eg = 240

[[psts]]
mg = 25
eg = 301

[[psts]]
mg = 46
eg = 331

[[psts]]
mg = 14
eg = 348

[[psts]]
mg = 13
eg = 388

[[psts]]
mg = 0
eg = 404

[[psts]]
mg = 16
eg = 364

[[psts]]
mg = 51
eg = 357

[[psts]]
mg = 61
eg = 310

[[psts]]
mg = 52
eg = 296

[[psts]]
mg = 45
eg = 282

[[psts]]
mg = 24
eg = 378

[[psts]]
mg = 12
eg = 422

[[psts]]
mg = 32
eg = 389

[[psts]]
mg = 37
eg = 426

[[psts]]
mg = 91
eg = 286

[[psts]]
mg = 89
eg = 312

[[psts]]
mg = 10
eg = 286

[[psts]]
mg = -111
eg = 426

[[psts]]
mg = -26
eg = 428

[[psts]]
mg = -75
eg = 498

[[psts]]
mg = -48
eg = 524

[[psts]]
mg = 10
eg = 458

[[psts]]
mg = -123
eg = 441

[[psts]]
mg = -11
eg = 308

[[psts]]
mg = 118
eg = 278

[[psts]]
mg = 64
eg = 356

[[psts]]
mg = 67
eg = 386

[[psts]]
mg = 79
eg = 419

[[psts]]
mg = 61
eg = 447

[[psts]]
mg = 48
eg = 429

[[psts]]
mg = 5
eg = 411

[[psts]]
mg = 55
eg = 350

[[psts]]
mg = 5
eg = -181

[[psts]]
mg = 32
eg = -90

[[psts]]
mg = -32
eg = -39

[[psts]]
mg = -118
eg = -56

[[psts]]
mg = -105
eg = -78

[[psts]]
mg = -110
eg = -30

[[psts]]
mg = 55
eg = -91

[[psts]]
mg = 48
eg = -219

[[psts]]
mg = 13
eg = -51

[[psts]]
mg = -25
eg = -4

[[psts]]
mg = -67
eg = 32

[[psts]]
mg = -179
eg = 69

[[psts]]
mg = -151
eg = 54

[[psts]]
mg = -113
eg = 43

[[psts]]
mg = -6
eg = -13

[[psts]]
mg = 40
eg = -76

[[psts]]
mg = -141
eg = -9

[[psts]]
mg = -55
eg = 29

[[psts]]
mg = -64
eg = 70

[[psts]]
mg = -106
eg = 109

[[psts]]
mg = -81
eg = 100

[[psts]]
mg = -62
eg = 69

[[psts]]
mg = -42
eg = 23

[[psts]]
mg = -117
eg = -18

[[psts]]
mg = -155
eg = -20

[[psts]]
mg = 31
eg = 49

[[psts]]
mg = 33
eg = 97

[[psts]]
mg = -38
eg = 138

[[psts]]
mg = -11
eg = 134

[[psts]]
mg = 49
eg = 93

[[psts]]
mg = 46
eg = 49

[[psts]]
mg = -119
eg = -33

[[psts]]
mg = -108
eg = 26

[[psts]]
mg = 132
eg = 79

[[psts]]
mg = 159
eg = 111

[[psts]]
mg = 76
eg = 132

[[psts]]
mg = 139
eg = 120

[[psts]]
mg = 182
eg = 104

[[psts]]
mg = 138
eg = 79

[[psts]]
mg = -115
eg = 12

[[psts]]
mg = 14
eg = 20

[[psts]]
mg = 302
eg = 94

[[psts]]
mg = 364
eg = 83

[[psts]]
mg = 295
eg = 70

[[psts]]
mg = 254
eg = 71

[[psts]]
mg = 331
eg = 80

[[psts]]
mg = 256
eg = 94

[[psts]]
mg = -6
eg = 14

[[psts]]
mg = -35
eg = -72

[[psts]]
mg = 280
eg = 71

[[psts]]
mg = 281
eg = 45

[[psts]]
mg = 397
eg = -16

[[psts]]
mg = 243
eg = 10

[[psts]]
mg = 379
eg = 28

[[psts]]
mg = 155
eg = 94

[[psts]]
mg = 146
eg = -116

[[psts]]
mg = 168
eg = -409

[[psts]]
mg = 539
eg = -187

[[psts]]
mg = 408
eg = -114

[[psts]]
mg = 366
eg = -52

[[psts]]
mg = 443
eg = -111

[[psts]]
mg = 340
eg = -93

[[psts]]
mg = 499
eg = -125

[[psts]]
mg = 28
eg = -404
